FROM node:12

COPY . /opt/app

# WORKDIR /opt/app/uxser-microservice
WORKDIR /opt/app

RUN npm

# CMD yarn watch
# CMD npm start
CMD npm run start:prev

# FROM node:latest

# RUN mkdir -p /usr/src/app
# WORKDIR /usr/src/app

# COPY package.json /usr/src/app/package.json
# RUN npm install

# COPY . /usr/src/app